[package]
name = "connectome-model"
version = "0.1.0"
authors = ["aemino <aeminodev@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.23.1"
petgraph = "0.5.1"
rand = "0.7.3"
rand_distr = "0.3.0"
rayon = "1.5.0"
bimap = "0.5.3"
